apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: my-flyway-custom:latest
          imagePullPolicy: IfNotPresent
          command: ["flyway"]
          args:
            [
              "-url=jdbc:mysql://mariadb.default.svc.cluster.local:3306/stevedb",
              "-user=steve",
              "-password=stevepass",
              "migrate",
            ]
      restartPolicy: Never
      initContainers:
        - name: wait-for-mariadb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mariadb 3306; do echo waiting for mariadb; sleep 3; done",
            ]
