apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq
      version: 12.1.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: user
      password: bitnami
      erlangCookie: mycookie
    service:
      type: ClusterIP
