apiVersion: apps/v1
kind: Deployment
metadata:
  name: steve
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steve
  template:
    metadata:
      labels:
        app: steve
    spec:
      containers:
        - name: steve
          image: steve-steve:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: steve-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: steve
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
