apiVersion: apps/v1
kind: Deployment
metadata:
  name: steve
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steve
  template:
    metadata:
      labels:
        app: steve
    spec:
      containers:
        - name: steve
          image: steve-steve:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
    initContainers:
      - name: wait-for-mariadb
        image: busybox
        command:
          [
            "sh",
            "-c",
            "until nc -z mariadb 3306; do echo waiting for mariadb; sleep 3; done",
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: steve-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: steve
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
