apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      containers:
        - name: wiremock
          image: wiremock/wiremock:2.35.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: wiremock
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
